name: Freaks Catalog Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'
    - name: Run tests
      run: xcodebuild test -scheme 'Freaks' -project 'Freaks.xcodeproj' -destination 'platform=iOS Simulator,name=iPhone 12'